/**
 * Build Script Contracts for Speck Public Website
 *
 * These TypeScript interfaces define the APIs for build-time scripts,
 * particularly the documentation sync script.
 *
 * Phase: 1 (Design & Contracts)
 * Date: 2025-11-15
 */

// ============================================================================
// Documentation Sync Script (scripts/sync-docs.ts)
// ============================================================================

export interface SyncDocsConfig {
  /** Main repository URL. Default: from MAIN_REPO_URL env var */
  mainRepoUrl?: string;
  /** Path to docs directory in main repo. Default: "docs" */
  docsSourcePath?: string;
  /** Target directory for synced docs. Default: "src/content/docs" */
  targetDir?: string;
  /** Temporary directory for Git clone. Default: ".temp-docs-clone" */
  tempDir?: string;
  /** If true, don't actually sync (for testing). Default: false */
  dryRun?: boolean;
}

export interface SyncDocsResult {
  /** True if sync completed successfully */
  success: boolean;
  /** Number of files synced (copied to target directory) */
  filesSynced: number;
  /** List of synced file paths (relative to docs root) */
  filesCloned: string[];
  /** Error message if sync failed */
  error?: string;
  /** True if using cached docs from previous build (sync failed) */
  usingCachedDocs: boolean;
  /** Timestamp of sync completion */
  timestamp: Date;
}

export interface SyncDocsError extends Error {
  code: SyncDocsErrorCode;
  details?: Record<string, unknown>;
}

export enum SyncDocsErrorCode {
  /** Main repository URL is invalid or unreachable */
  REPO_UNREACHABLE = 'REPO_UNREACHABLE',
  /** Git is not installed or not in PATH */
  GIT_NOT_INSTALLED = 'GIT_NOT_INSTALLED',
  /** Specified docs path doesn't exist in main repo */
  DOCS_PATH_NOT_FOUND = 'DOCS_PATH_NOT_FOUND',
  /** No cached docs available and sync failed */
  NO_FALLBACK_AVAILABLE = 'NO_FALLBACK_AVAILABLE',
  /** Git sparse checkout command failed */
  SPARSE_CHECKOUT_FAILED = 'SPARSE_CHECKOUT_FAILED',
  /** File copy operation failed */
  COPY_FAILED = 'COPY_FAILED',
}

// ============================================================================
// Environment Variables
// ============================================================================

export interface BuildEnvironment {
  /** Main Speck repository URL (e.g., "https://github.com/nprbst/speck.git") */
  MAIN_REPO_URL: string;
  /** Path to docs in main repo (e.g., "docs") */
  DOCS_SOURCE_PATH: string;
  /** Cloudflare Pages environment (set automatically) */
  CF_PAGES?: string;
  /** Cloudflare Pages branch being built */
  CF_PAGES_BRANCH?: string;
  /** Cloudflare Pages commit SHA */
  CF_PAGES_COMMIT_SHA?: string;
}

// ============================================================================
// Astro Content Collection Types (for type generation)
// ============================================================================

/**
 * This type is generated by Astro based on src/content/config.ts schema.
 * Included here for documentation purposes.
 */
export interface ContentCollectionEntry {
  id: string;
  slug: string;
  body: string;
  collection: 'docs';
  data: {
    title: string;
    description: string;
    category: 'getting-started' | 'commands' | 'concepts' | 'examples';
    order: number;
    lastUpdated?: Date;
    tags?: string[];
  };
  render(): Promise<{
    Content: any; // Astro component
    headings: Array<{
      depth: number;
      slug: string;
      text: string;
    }>;
  }>;
}

// ============================================================================
// Build Performance Budgets
// ============================================================================

export interface PerformanceBudgets {
  /** Max total page weight in KB (compressed) */
  maxPageWeight: 500;
  /** Max JavaScript bundle size in KB (compressed) */
  maxJavaScriptSize: 10;
  /** Max time to First Contentful Paint on 3G (seconds) */
  maxFCP: 1.5;
  /** Max Cumulative Layout Shift */
  maxCLS: 0.1;
  /** Max Time to Interactive on 3G (seconds) */
  maxTTI: 3.5;
  /** Min Lighthouse accessibility score */
  minAccessibilityScore: 95;
  /** Min Lighthouse performance score */
  minPerformanceScore: 90;
  /** Min Lighthouse best practices score */
  minBestPracticesScore: 95;
}

export const DEFAULT_BUDGETS: PerformanceBudgets = {
  maxPageWeight: 500,
  maxJavaScriptSize: 10,
  maxFCP: 1.5,
  maxCLS: 0.1,
  maxTTI: 3.5,
  minAccessibilityScore: 95,
  minPerformanceScore: 90,
  minBestPracticesScore: 95,
};

// ============================================================================
// Lighthouse CI Configuration
// ============================================================================

export interface LighthouseConfig {
  /** URLs to audit (relative to site root) */
  urls: string[];
  /** Number of runs per URL (median result used) */
  numberOfRuns: number;
  /** Performance budgets to enforce */
  budgets: PerformanceBudgets;
  /** Device emulation settings */
  emulatedFormFactor: 'mobile' | 'desktop';
  /** Network throttling preset */
  throttling: 'mobileSlow4G' | 'mobile3G' | 'none';
}

export const DEFAULT_LIGHTHOUSE_CONFIG: LighthouseConfig = {
  urls: ['/', '/docs/getting-started/quick-start', '/comparison'],
  numberOfRuns: 3,
  budgets: DEFAULT_BUDGETS,
  emulatedFormFactor: 'mobile',
  throttling: 'mobile3G',
};
